### ISSUE TITLE
my 9th drive wont work

### ISSUE THREAD

**Issue by WeeMellowToby** [Sammy1Am/Moppy2#165]
I have pin 18 plugged into a5 and pin 20 plugged into a4. All other pins seem to work with the drive im using and all my other drives don't work with it
(proof my audio file has track 9)
![image](https://user-images.githubusercontent.com/69983951/181814469-8ee868a3-ca54-4794-a3c4-9e52de5ae745.png)

**Comment by Sammy1Am** [comment]
Thanks for checking with other drives and confirming the MIDI has a 9th channel (those would all have been my first things to check).  It looks like you'll actually need to [modify this line](https://github.com/Sammy1Am/Moppy2/blob/f29bb48662e88dfcc02dcfe56122ab190d12693e/Microcontroller/Moppy2-Arduino/src/MoppyInstruments/FloppyDrives.h#L43) to have a `9` instead of an `8`.  I *think* (hope) that's all that needs to be changed in the code; I only ever had 8 drives hooked up so I haven't done thorough testing with 9.
