### ISSUE TITLE
How do I use hard drives

### ISSUE THREAD

**Issue by Riku32** [Sammy1Am/Moppy2#79]
I see people using hard drives in youtube videos. How would I go about using my spare low capacity hard drives to play music?

**Comment by SammyIAm** [comment]
[A few other people have asked this previously](https://github.com/SammyIAm/Moppy2/issues?utf8=%E2%9C%93&q=is%3Aissue+hdd), so it's worth checking out those threads and maybe their GitHub pages to see if there's any useful information there.

To give a brief overview though:

- There's not really any way to do this using the HDD's circuitry, so you'll need to wire something directly into the coils that control the read head.
- I have no idea what the current requirements to swing the head around are, so you *might* be able to drive them directly from the Arduino, but you might need to use a transistor instead.
- If you want to play notes using the drives, you probably won't need to modify the Moppy code at all since the output of the `STEP` pins is essentially already a square wave usable to produce tones.
- If you want to use the drives as percussion instruments, you'll want to **only** send a brief signal for MIDI note-on events, so you'd want to modify the Arduino Moppy code a bit to make that happen.
